[Standard]

theme = "dark"

number = true

currentNumber = true

cursorLine = false

statusLine = true

tabLine = true

syntax = true

indentationLines = true

tabStop = 2

autoCloseParen = true

autoIndent = true

ignorecase = true

smartcase = true

disableChangeCursor = false

defaultCursor = "blinkBlock"

normalModeCursor = "blinkBlock"

insertModeCursor = "blinkIbeam"

autoSave = false

autoSaveInterval = 5

liveReloadOfConf = false

incrementalSearch = true

popUpWindowInExmode = true

autoDeleteParen = false

smoothScroll = true

smoothScrollSpeed = 15

[Clipboard]
enable = true

# toolOnLinux = "xsel"

[BuildOnSave]

enable = false

# workspaceRoot = "/home/fox/git/moe"

# command = "cd /home/fox/git/moe && nimble build"

[TabLine]

allBuffer = false

[StatusLine]

multipleStatusLine = true

merge = false

mode = true

filename = true

chanedMark = true

line = true

column = true

encoding = true

language = true

directory = true

gitbranchName = true

showGitInactive = false

showModeInactive = false


[Highlight]

currentLine = true

reservedWord = ["TODO", "WIP", "NOTE"]

replaceText = true

pairOfParen = true

fullWidthSpace = true

trailingSpaces = true

currentWord = true

[AutoBackup]

enable = true

# 10 second
idleTime = 10

# 5 minute
interval = 5

# backupDir = "/home/fox/Nim"

dirToExclude = ["/etc"]

[QuickRun]

saveBufferWhenQuickRun = true

# command = "nimble build"

# 30 second
timeout = 30

# nimAdvancedCommand = "js"

# ClangOptions = "-Wall"

# CppOptions = "-Wall"

# NimOptions = "--debugger:native"

# shOptions = "-c"

# bashOptions = "-c"

[Notification]

screenNotifications = true

logNotifications = true

autoBackupScreenNotify = true

autoBackupLogNotify = true

autoSaveScreenNotify = true

autoSaveLogNotify = true

yankScreenNotify = true

yankLogNotify = true

deleteScreenNotify = true

deleteLogNotify = true

saveScreenNotify = true

saveLogNotify = true

quickRunScreenNotify = true

quickRunLogNotify = true

buildOnSaveScreenNotify = true

buildOnSaveLogNotify = true

filerScreenNotify = true

filerLogNotify = true

restoreScreenNotify = true

restoreLogNotify = true

[Filer]

showIcons = true

[Autocomplete]

enable = true

[Persist]

exCommand = true

search = true

cursorPosition = true

[Debug.WindowNode]
enable = true
currentWindow = true
index = true
windowIndex = true
bufferIndex = true
parentIndex = true
childLen = true
splitType = true
haveCursesWin = true
y = true
x = true
h = true
w = true
currentLine = true
currentColumn = true
expandedColumn = true
cursor = true

[Debug.EditorView]
enable = true
widthOfLineNum = true
height = true
width = true
originalLine = false
start = false
length = false

[Debug.BufferStatus]
enable = true
bufferIndex = true
path = true
openDir = true
currentMode = true
prevMode = true
language = true
encoding = true
countChange = true
cmdLoop = true
lastSaveTime = true
bufferLen = true

[Theme]

baseTheme = "dark"

editorBg = "default"
lineNum = "gray54"
lineNumBg = "default"
currentLineNum = "teal"
currentLineNumBg = "default"
# statsu bar
statusLineNormalMode = "white"
statusLineNormalModeBg = "blue"
statusLineModeNormalMode = "black"
statusLineModeNormalModeBg = "white"
statusLineNormalModeInactive = "blue"
statusLineNormalModeInactiveBg = "white"

statusLineInsertMode = "white"
statusLineInsertModeBg = "blue"
statusLineModeInsertMode = "black"
statusLineModeInsertModeBg = "white"
statusLineInsertModeInactive = "blue"
statusLineInsertModeInactiveBg = "white"

statusLineVisualMode = "white"
statusLineVisualModeBg = "blue"
statusLineModeVisualMode = "black"
statusLineModeVisualModeBg = "white"
statusLineVisualModeInactive = "blue"
statusLineVisualModeInactiveBg = "white"

statusLineReplaceMode = "white"
statusLineReplaceModeBg = "blue"
statusLineModeReplaceMode = "black"
statusLineModeReplaceModeBg = "white"
statusLineReplaceModeInactive = "blue"
statusLineReplaceModeInactiveBg = "white"

statusLineFilerMode = "white"
statusLineFilerModeBg = "blue"
statusLineModeFilerMode = "black"
statusLineModeFilerModeBg = "white"
statusLineFilerModeInactive = "blue"
statusLineFilerModeInactiveBg = "white"

statusLineExMode = "white"
statusLineExModeBg = "blue"
statusLineModeExMode = "black"
statusLineModeExModeBg = "white"
statusLineExModeInactive = "blue"
statusLineExModeInactiveBg = "white"

statusLineGitBranch = "white"
statusLineGitBranchBg = "blue"

# tab line
tab = "white"
tabBg = "default"
currentTab = "white"
currentTabBg = "blue"

# command  bar
commandBar = "gray100"
commandBarBg = "default"

# error message
errorMessage = "red"
errorMessageBg = "default"

# search result highlighting
searchResult = "default"
searchResultBg = "red"

# selected area in visual mode
visualMode = "gray100"
visualModeBg = "purple_1"

# color scheme
defaultChar = "white"
gtKeyword = "skyBlue1"
gtFunctionName = "gold1"
gtTypeName = "green"
gtBoolean = "yellow"
gtStringLit = "yellow"
gtSpecialVar = "green"
gtBuiltin = "yellow"
gtDecNumber = "aqua"
gtComment = "gray"
gtLongComment = "gray"
gtWhitespace = "gray"
gtPreprocessor = "green"

# filer mode
currentFile = "gray100"
currentFileBg = "teal"
file = "gray100"
fileBg = "default"
dir = "blue"
dirBg = "default"
pcLink = "teal"
pcLinkBg = "default"

# pop up window
popUpWindow = "gray100"
popUpWindowBg = "black"
popUpWinCurrentLine = "blue"
popUpWinCurrentLineBg = "black"

# replace text highlighting
replaceText = "default"
replaceTextBg = "red"

# pair of paren highlighting
parenText = "default"
parenTextBg = "blue"

# highlight other uses current word
currentWord = "default"
currentWordBg = "gray"

# highlight full width space
highlightFullWidthSpace = "red"
highlightFullWidthSpaceBg = "red"

# highlight trailing spaces
highlightTrailingSpaces = "red"
highlightTrailingSpacesBg = "red"

# highlight reserved words
reservedWord = "white"
reservedWordBg = "gray"

# configuration mode
currentSetting = "gray100"
currentSettingBg = "teal"

# highlight current line background
currentLineBg = "gray27"
