language: c
compiler:
  - gcc
before_install:
  # Install nim
  - git clone -b devel git://github.com/nim-lang/Nim.git --depth 1
  - cd Nim
  - git clone --depth 1 git://github.com/nim-lang/csources
  - cd csources && sh build.sh
  - cd ..
  - bin/nim c koch
  - ./koch boot -d:release
  - export PATH=$PWD/bin:$PATH
  - cd ..
script:
  nimble test
  nimble build
